#ifndef UART1_H
#define UART1_H

#include "driver/uart.h"
#include "esp_log.h"
#include "sdkconfig.h"

static const char *TAG = "uart1";

#define UART_PORT_NUM UART_NUM_1
#define UART_TX_PIN CONFIG_UART1_TX_PIN
#define UART_RX_PIN CONFIG_UART1_RX_PIN
#define UART_BUF_SIZE CONFIG_UART1_BUF_SIZE
#define UART_BAUD_RATE CONFIG_UART1_BAUD_RATE
#define UART_DATA_BITS CONFIG_UART1_DATA_BITS
#define UART_STOP_BITS CONFIG_UART1_STOP_BITS

#if CONFIG_UART1_PARITY_DISABLE
#define UART_PARITY UART_PARITY_DISABLE
#elif CONFIG_UART1_PARITY_EVEN
#define UART_PARITY UART_PARITY_EVEN
#elif CONFIG_UART1_PARITY_ODD
#define UART_PARITY UART_PARITY_ODD
#else
#define UART_PARITY UART_PARITY_DISABLE
#endif

#if CONFIG_UART1_FLOWCTRL_DISABLE
#define UART_FLOW_CTRL UART_HW_FLOWCTRL_DISABLE
#elif CONFIG_UART1_FLOWCTRL_RTS
#define UART_FLOW_CTRL UART_HW_FLOWCTRL_RTS
#elif CONFIG_UART1_FLOWCTRL_CTS
#define UART_FLOW_CTRL UART_HW_FLOWCTRL_CTS
#elif CONFIG_UART1_FLOWCTRL_RTS_CTS
#define UART_FLOW_CTRL UART_HW_FLOWCTRL_RTS_CTS
#else
#define UART_FLOW_CTRL UART_HW_FLOWCTRL_DISABLE
#endif

void uart1_init(void);

#endif
